//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDLPROJET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiqueprix
    {
        public int historiqueprixID { get; set; }
        public Nullable<int> produitID { get; set; }
        public Nullable<int> prixdeventeunitaire { get; set; }
        public Nullable<System.DateTime> datemodification { get; set; }
    
        public virtual produit produit { get; set; }
    }
}
