//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDLPROJET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payement
    {
        public int IDpayement { get; set; }
        public Nullable<int> montant_total { get; set; }
        public Nullable<int> montant_paye { get; set; }
        public Nullable<int> montant_restant { get; set; }
    }
}
