//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDLPROJET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.historiquefacturations = new HashSet<historiquefacturation>();
            this.historiquefacturations1 = new HashSet<historiquefacturation>();
            this.historiquefacturations2 = new HashSet<historiquefacturation>();
            this.historiquefacturations3 = new HashSet<historiquefacturation>();
            this.historiqueprixes = new HashSet<historiqueprix>();
            this.tableachats = new HashSet<tableachat>();
        }
    
        public int produitID { get; set; }
        public Nullable<int> categorieID { get; set; }
        public Nullable<int> fournisseurID { get; set; }
        public string nomproduit { get; set; }
        public Nullable<int> prixdeventeunitaire { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string prixunitaireachat { get; set; }
        public Nullable<System.DateTime> dateentree { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual fournisseur fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiquefacturation> historiquefacturations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiquefacturation> historiquefacturations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiquefacturation> historiquefacturations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiquefacturation> historiquefacturations3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiqueprix> historiqueprixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tableachat> tableachats { get; set; }
    }
}
