//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRDLPROJET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public Nullable<int> profileID { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string useremail { get; set; }
        public Nullable<System.DateTime> dateinsertion { get; set; }
    
        public virtual profil profil { get; set; }
    }
}
